name: test-my-project
on: 
  - push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: inst-poetry
        run: |
          pip install poetry
          make install
      - name: linter
        run: make lint
